version: '3.8'

services:
  php_container:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000
    depends_on:
      - mysql_container

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/EncounterAPI/public/:/app/apps/EncounterAPI/public
    depends_on:
      - php_container

  mysql_container:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWD}
    ports:
      - 3306:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    volumes:
      - ./var/MySQL:/var/lib/mysql

  mongodb:
    image: mongo:5.0
    container_name: mongodb_container
    ports:
      - 27017:${MONGODB_PORT}
    volumes:
      - ./var/mongo:/data/db
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWD}

